name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you are publishing the package

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  video_player: ^2.7.0

  # Your other dependencies here
  # For example, if you're using the 'http' package, you would list it like this:
  # http: ^0.14.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  # Your other dev dependencies here

flutter:
  uses-material-design: true
  assets:
    - assets/login_page.png
    - assets/logo.jpeg
    - assets/logo_name.jpeg